views/dashboard/views.py
import sys
sys.path.append("../../")
from libraries.libraries import *
from processes.dashboarddefaults.defaults import dashboardDeafults

dashboard_main = Blueprint("dashboard_main", __name__, static_folder="static", template_folder="templates")


@dashboard_main.route("/dashboard", methods=["GET", "POST"])
def dashboard():
    if "username" in session:
        dropdowndata = dashboardDeafults.partDropDown()
        start_date = str((datetime.now() - timedelta(days=15)).strftime('%Y-%m-%d'))
        end_date = str(datetime.now().strftime('%Y-%m-%d'))
        cardData = dashboardDeafults.dataCards(start_date, end_date, partnames=dashboardDeafults.partDropDown())[0]
        graphingData = dashboardDeafults.dataCards(start_date, end_date, partnames=dashboardDeafults.partDropDown())[1]
        if request.method == "POST":
            date_range = request.form.get("daterange")
            if date_range:
                start_date, end_date = date_range.split(" to ")
                start_date = str(datetime.strptime(start_date, '%Y-%m-%d')).split()[0]
                end_date = str(datetime.strptime(end_date, '%Y-%m-%d')).split()[0]
            else:
                start_date, end_date = None, None
            
            selected_parts = request.form.getlist("parts")
            
            cardData = dashboardDeafults.dataCards(start_date, end_date, selected_parts)[0]
            graphingData = dashboardDeafults.dataCards(start_date, end_date, selected_parts)[1]
            
            return render_template("dashboard.html", current_page="dashboard", dropdowndata=dropdowndata, totalworkorders=cardData["totalWorkOrders"], totalweight=cardData["totalWeight"], totalsalesorders=cardData["totalSalesOrders"], totalpurchaseorders=cardData["totalPurchaseOrders"], graphingData=graphingData, start_date=start_date, end_date=end_date)
            
        return render_template("dashboard.html", current_page="dashboard", dropdowndata=dropdowndata, totalworkorders=cardData["totalWorkOrders"], totalweight=cardData["totalWeight"], totalsalesorders=cardData["totalSalesOrders"], totalpurchaseorders=cardData["totalPurchaseOrders"], graphingData=graphingData, start_date=start_date, end_date=end_date)
    else:
        return redirect(url_for("login_main.login"))
    
    

views/dashboard/templates/dashboard.html
{% extends "dashboard_base.html" %}

{% block title %}
    Dashboard | Alimex
{% endblock title %}

{% block body %}
    <div class="dashboardMain is-flex is-flex-direction-row">
        {% include "navbarpostlogin.html" %}
        <div class="dashboardMainContent is-flex is-flex-direction-column">
            <div class="dashboardMainContentControls is-flex is-flex-direction-row">
                <form class="is-flex is-flex-direction-row is-align-items-center is-justify-space_between" method="POST" action="{{url_for('dashboard_main.dashboard')}}">
                    <p>Dashboard</p>
                    <div class="is-flex is-flex-direction-row is-align-items-center is-justify-content-space-around" name=daterangediv>
                        <img src="../../../static/assets/images/selectdateicon.svg" alt="selectdateicon"/>
                        <input type="text" id="daterange" name="daterange" placeholder="Select Date" required>
                        <img src="../../../static/assets/images/dropdownarrow.svg" alt="dropdownarrowicon"/>
                    </div>
                    <div class="is-flex is-flex-direction-column">
                        <div class="is-flex is-flex-direction-row is-align-items-center is-justify-content-flex-start" onclick="toggleDropDown(event)">
                            <img src="../../../static/assets/images/selectparticon.svg" alt="selectparticon"/>
                            <p>Select Part</p>
                            <img src="../../../static/assets/images/dropdownarrow.svg" alt="dropdownarrowicon"/>
                        </div>
                        <div class="dropDownList is-flex is-flex-direction-column" name="dropDownList" id="dropDownList">
                            {% for element in dropdowndata %}
                                <div class="is-flex is-flex-direction-row is-clickable" onclick="toggleCheckbox(event, 'checkbox{{ loop.index }}')">
                                    <input type="checkbox" name="parts" id="checkbox{{ loop.index }}" value="{{ element }}"/>
                                    <label for="checkbox{{ loop.index }}">{{ element }}</label>
                                </div>
                            {% endfor %}
                        </div>
                    </div>
                    <button class="analyze is-flex is-flex-direction-row is-align-items-center is-justify-content-center is-text-centered" type="submit" id="analyze" name="analyze">Analyze</button>
                </form>
            </div>
            <div class="mainDataCard is-flex is-flex-direction-column is-align-items-left is-justify-content-space-around">
                <p>Sales Summary</p>
                <div class="mainDataCardItems is-flex is-flex-direction-row is-align-items-center">
                    <div class="workOrders is-flex is-flex-direction-row is-align-items-center is-justify-content-space-between is-clickable">
                        <img src="../../../static/assets/images/workorderimage.svg" alt="workorderimage"/>
                        <div class="workOrdersText is-flex is-flex-direction-column has-text-right">
                                <p>{{ totalworkorders }}</p>
                                <p>Total Work Orders</p>
                        </div>
                    </div>
                    <div class="weight is-flex is-flex-direction-row is-align-items-center is-justify-content-space-between is-clickable">
                        <img src="../../../static/assets/images/totalweightimage.svg" alt="totalweightimage"/>
                        <div class="weightText is-flex is-flex-direction-column has-text-right">
                                <p>{{ totalweight }}</p>
                                <p>Total Weight / Kg</p>
                        </div>
                    </div>
                    <div class="salesOrders is-flex is-flex-direction-row is-align-items-center is-justify-content-space-between is-clickable">
                        <img src="../../../static/assets/images/totalsoimage.svg" alt="totalsoimage"/>
                        <div class="salesOrdersText is-flex is-flex-direction-column has-text-right">
                                <p>{{ totalsalesorders }}</p>
                                <p>Total Sales Orders</p>
                        </div>
                    </div>
                    <div class="purchaseOrders is-flex is-flex-direction-row is-align-items-center is-justify-content-space-between is-clickable">
                        <img src="../../../static/assets/images/totalpoimage.svg" alt="totalpoimage"/>
                        <div class="purchaseOrdersText is-flex is-flex-direction-column has-text-right">
                                <p>{{ totalpurchaseorders }}</p>
                                <p>Total Purchase Orders</p>
                        </div>
                    </div>
                </div>
            </div>
            <div class="visualizationTop tabs is-boxed is-flex is-flex-direction-row is-align-items-center is-justify-content-flex-start">
                <li class="is-active" onclick="selected(this, 'weightChartData')">
                    <a class="is-flex is-flex-direction-column">
                        <span>Weight (kg)</span>
                    </a>
                </li>
                <li onclick="selected(this, 'thicknessChartData')">
                    <a>
                        <span>Thickness (mm)</span>
                    </a>
                </li>
            </div>
            <div class="dataCharts is-flex is-flex-direction-row">
                <canvas class="barChart" id="barChart"></canvas>
            </div>
            <div class="scatterCharts is-flex is-flex-direction-row">
                <canvas class="scatterPlot" id="scatterPlot"></canvas>
            </div>
            <p class="is-flex is-flex-direction-row is-align-items-center is-justify-content-center">@2024 Alimex ACP Asia. All Rights Received</p>
        </div>
    </div>
    <script type="text/javascript">
        const graphingData = {{ graphingData | tojson }};
        const startDate = "{{ start_date }}";
        const endDate = "{{ end_date }}";


    </script>
{% endblock body %}

views/dashboard/templates/dashboard_base.html
<!doctype html>
<html lang="en">

<head>
    <!-- Required Meta Tags -->
    <meta charset="utf-8">
    <meta name="description" content="Alimex ACP Asia Sdn Bhd">
    <meta name="keywords" content="HTML, CSS, XML, JavaScript">
    <meta name="author" content="Alimex ACP Asia Sdn Bhd">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <!-- -->
    
    <!-- CDN Deployedment StyleSheets-->
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css" />
    <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@1.0.1/css/bulma.min.css">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/views/dashboard/style.css')}}"/>
    <!-- -->

    <!-- CDN Deployedment JavaScript-->
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/chartjs-plugin-datalabels@2.0.0"></script>
    <script type="text/javascript" src="https://cdn.jsdelivr.net/jquery/1/jquery.min.js"></script>
    <script type="text/javascript" src="https://cdn.jsdelivr.net/momentjs/latest/moment.min.js"></script>
    <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.min.js"></script>
    <script src="{{ url_for('static', filename='/javascript/script.js')}}"></script>

    <!-- -->

    <!-- CDN Deployedment Fonts and Animations-->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Outfit:wght@100..900&display=swap" rel="stylesheet">
    <!-- -->
    
    <title>
        {% block title %}{% endblock %}
    </title>

</head>

<body>
    {% block body %}{% endblock body %}
</body>

</html>