views/login/views.py
import sys
sys.path.append("../../")
from libraries.libraries import *
from processes.login.login import loginSystem

login_main = Blueprint("login_main", __name__, static_folder="static", template_folder="templates")

@login_main.route("/", methods=["GET", "POST"])
def login():
    if request.method == "POST":
        username_email = request.form["usernameInput"]
        password = request.form["passwordInput"]
        login_data = loginSystem.userLogin(username_email, password)
        if isinstance(login_data, dict):
            session["id"] = login_data["id"]
            session["username"] = login_data["username"]
            session["email"] = login_data["email"]
            session["fname"] = login_data["fname"]
            session["lname"] = login_data["lname"]
            return redirect(url_for("dashboard_main.dashboard"))
        else:
            return render_template("login.html", prompt=login_data)
    return render_template('login.html')

views/login/templates/login.html
{% extends "login_base.html" %}

{% block title %}
    Login | Alimex
{% endblock title %}

{% block body %}
    <div class="loginMain is-flex is-flex-direction-row is-justify-content-space-evenly">
        <div class="is-flex is-flex-direction-row">
            <img src="../../../static/assets/images/alimexlogo.png" alt="alimexlogo"/>
            <form class="loginForm is-flex is-flex-direction-column is-align-items-center is-justify-content-center" method="POST" action="{{url_for('login_main.login')}}">
                <p class="has-text-centered">LOGIN</p>
                <p class="has-text-centered">Login with username or email address</p>
                <div class="loginFormUsername is-flex is-flex-direction-row is-align-items-center">
                    <img src="../../../static/assets/images/usernameimage.svg" alt="usernameimage"/>
                    <input type="text" placeholder="Username/Email" id="usernameInput" name="usernameInput"/>
                </div>
                <div class="loginFormPassword is-flex is-flex-direction-row is-align-items-center">
                    <img src="../../../static/assets/images/passwordimage.svg" alt="passwordimage"/>
                    <input type="password" placeholder="Password" id="passwordInput" name="passwordInput"/>
                </div>
                <button type="submit" id="loginButton" name="loginButton">Login</button>
            </form>
        </div>
        <div class="is-flex is-flex-direction-row">
        </div>
        {% if prompt %}
            <script>
                alert("{{ prompt }}");
            </script>
        {% endif %}
    </div>
    <script type="text/javascript">
        function preventDefault(e) {
            e.preventDefault();
        }

        function disableScroll() {
            // Add touchmove event listener to document body
            document.body.addEventListener('touchmove', preventDefault, { passive: false });
            // Add touchstart event listener to document body
            document.body.addEventListener('touchstart', preventDefault, { passive: false });

            // Allow touch events on input fields
            let inputs = document.querySelectorAll('input, textarea, select, button');
            inputs.forEach(input => {
                input.addEventListener('touchstart', function(e) {
                    e.stopPropagation();
                });
                input.addEventListener('touchmove', function(e) {
                    e.stopPropagation();
                });
            });
        }

        function enableScroll() {
            // Remove touchmove event listener from document body
            document.body.removeEventListener('touchmove', preventDefault);
            // Remove touchstart event listener from document body
            document.body.removeEventListener('touchstart', preventDefault);

            // Remove touch event listeners from input fields
            let inputs = document.querySelectorAll('input, textarea, select, button');
            inputs.forEach(input => {
                input.removeEventListener('touchstart', function(e) {
                    e.stopPropagation();
                });
                input.removeEventListener('touchmove', function(e) {
                    e.stopPropagation();
                });
            });
        }

        disableScroll();
    </script>
{% endblock body %}

views/login/templates/login_base.html
<!doctype html>
<html lang="en">

<head>
    <!-- Required Meta Tags -->
    <meta charset="utf-8">
    <meta name="description" content="Alimex ACP Asia Sdn Bhd">
    <meta name="keywords" content="HTML, CSS, XML, JavaScript">
    <meta name="author" content="Alimex ACP Asia Sdn Bhd">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <!-- -->
    
    <!-- CDN Deployedment StyleSheets-->
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@1.0.1/css/bulma.min.css">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/views/login/style.css')}}"/>
    <!-- -->

    <!-- CDN Deployedment JavaScript-->
    <script src="{{ url_for('static', filename='/javascript/script.js')}}"></script>
    <!-- -->

    <!-- CDN Deployedment Fonts and Animations-->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Outfit:wght@100..900&display=swap" rel="stylesheet">
    <!-- -->
    
    <title>
        {% block title %}{% endblock %}
    </title>

</head>

<body>
    {% block body %}{% endblock body %}
</body>

</html>